<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mappings\**" />
    <Compile Remove="Repositories\**" />
    <Compile Remove="Tests\UnitTests\Common\**" />
    <Compile Remove="Tests\UnitTests\Helpers\**" />
    <Compile Remove="Tests\UnitTests\IntergrationTests\**" />
    <Compile Remove="Tests\UnitTests\Services\**" />
    <Compile Remove="Tests\UnitTests\TestData\**" />
    <Content Remove="Mappings\**" />
    <Content Remove="Repositories\**" />
    <Content Remove="Tests\UnitTests\Common\**" />
    <Content Remove="Tests\UnitTests\Helpers\**" />
    <Content Remove="Tests\UnitTests\IntergrationTests\**" />
    <Content Remove="Tests\UnitTests\Services\**" />
    <Content Remove="Tests\UnitTests\TestData\**" />
    <EmbeddedResource Remove="Mappings\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <EmbeddedResource Remove="Tests\UnitTests\Common\**" />
    <EmbeddedResource Remove="Tests\UnitTests\Helpers\**" />
    <EmbeddedResource Remove="Tests\UnitTests\IntergrationTests\**" />
    <EmbeddedResource Remove="Tests\UnitTests\Services\**" />
    <EmbeddedResource Remove="Tests\UnitTests\TestData\**" />
    <None Remove="Mappings\**" />
    <None Remove="Repositories\**" />
    <None Remove="Tests\UnitTests\Common\**" />
    <None Remove="Tests\UnitTests\Helpers\**" />
    <None Remove="Tests\UnitTests\IntergrationTests\**" />
    <None Remove="Tests\UnitTests\Services\**" />
    <None Remove="Tests\UnitTests\TestData\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
  </ItemGroup>

</Project>
