// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBBANDIENTHOAI.Data;

#nullable disable

namespace WEBBANDIENTHOAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301035746_AddSpinHistory")]
    partial class AddSpinHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LogId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.CartDetail", b =>
                {
                    b.Property<int>("CartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartDetailId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("OptionsPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOptions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartDetailId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Smartphones",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Các loại điện thoại thông minh"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Laptops",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Các loại máy tính xách tay"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.CrossSellRule", b =>
                {
                    b.Property<int>("CrossSellRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrossSellRuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisplayMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SuggestedProductId")
                        .HasColumnType("int");

                    b.Property<int>("TriggerProductId")
                        .HasColumnType("int");

                    b.HasKey("CrossSellRuleId");

                    b.HasIndex("SuggestedProductId");

                    b.HasIndex("TriggerProductId");

                    b.ToTable("CrossSellRules", (string)null);

                    b.HasData(
                        new
                        {
                            CrossSellRuleId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountedPrice = 40990000m,
                            DisplayMessage = "Hoàn thiện hệ sinh thái Apple 2026 của bạn!",
                            IsActive = true,
                            SuggestedProductId = 2,
                            TriggerProductId = 1
                        },
                        new
                        {
                            CrossSellRuleId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountedPrice = 61990000m,
                            DisplayMessage = "Bộ đôi làm việc đa nhiệm siêu mạnh mẽ",
                            IsActive = true,
                            SuggestedProductId = 4,
                            TriggerProductId = 3
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CitizenID")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TierId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Đường ABC, Quận 1, TP. HCM",
                            CitizenID = "0123456789",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@example.com",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            LoyaltyPoints = 0,
                            PasswordHash = new byte[] { 176, 65, 192, 174, 179, 91, 176, 250, 74, 166, 104, 202, 90, 146, 11, 89, 1, 150, 253, 175, 154, 0, 235, 133, 44, 155, 127, 77, 18, 60, 198, 214 },
                            Phone = "0987654321",
                            TierId = 1,
                            TotalSpent = 0m
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.CustomerTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<decimal>("BonusMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MinSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TierId");

                    b.ToTable("CustomerTiers", (string)null);

                    b.HasData(
                        new
                        {
                            TierId = 1,
                            BonusMultiplier = 1.0m,
                            Description = "Thành viên thường – nhận 1 điểm / 10.000đ",
                            MinSpending = 0m,
                            TierName = "Member"
                        },
                        new
                        {
                            TierId = 2,
                            BonusMultiplier = 1.2m,
                            Description = "Thành viên Bạc – Chi tiêu > 10Tr, hệ số điểm x1.2",
                            MinSpending = 10000000m,
                            TierName = "Silver"
                        },
                        new
                        {
                            TierId = 3,
                            BonusMultiplier = 1.5m,
                            Description = "Thành viên Vàng – Chi tiêu > 50Tr, hệ số điểm x1.5",
                            MinSpending = 50000000m,
                            TierName = "Gold"
                        },
                        new
                        {
                            TierId = 4,
                            BonusMultiplier = 2.0m,
                            Description = "Thành viên Kim Cương – Chi tiêu > 100Tr, hệ số điểm x2.0",
                            MinSpending = 100000000m,
                            TierName = "Diamond"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ExportReceipt", b =>
                {
                    b.Property<int>("ExportReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportReceiptId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExportReceiptId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("ExportReceipts", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ExportReceiptDetail", b =>
                {
                    b.Property<int>("ExportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportDetailId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExportReceiptId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SnapshotName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SnapshotSKU")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExportDetailId");

                    b.HasIndex("ExportReceiptId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExportReceiptDetails", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ImportReceipt", b =>
                {
                    b.Property<int>("ImportReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportReceiptId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ImportReceiptId");

                    b.ToTable("ImportReceipts", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ImportReceiptDetail", b =>
                {
                    b.Property<int>("ImportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportDetailId"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportReceiptId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SnapshotName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SnapshotSKU")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ImportDetailId");

                    b.HasIndex("ImportReceiptId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportReceiptDetails", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaximumQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InventoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockCode");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            CurrentQuantity = 100,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Kho A1",
                            MaximumQuantity = 1000,
                            MinimumQuantity = 15,
                            ProductId = 1,
                            StockCode = "SC-IP16PM256"
                        },
                        new
                        {
                            InventoryId = 2,
                            CurrentQuantity = 45,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Kho B2",
                            MaximumQuantity = 1000,
                            MinimumQuantity = 10,
                            ProductId = 2,
                            StockCode = "SC-MBP14M4"
                        },
                        new
                        {
                            InventoryId = 3,
                            CurrentQuantity = 80,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Kho A2",
                            MaximumQuantity = 1000,
                            MinimumQuantity = 20,
                            ProductId = 3,
                            StockCode = "SC-S24U256"
                        },
                        new
                        {
                            InventoryId = 4,
                            CurrentQuantity = 25,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Kho C1",
                            MaximumQuantity = 1000,
                            MinimumQuantity = 5,
                            ProductId = 4,
                            StockCode = "SC-DXPS16"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.InventoryHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryHistory", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.LaptopConfiguration", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationId"));

                    b.Property<string>("Battery")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CPU")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GraphicsCard")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ports")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RAM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScreenSize")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScreenTechnology")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Storage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Weight")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("LaptopConfigurations", null, t =>
                        {
                            t.HasTrigger("LaptopConfigTrigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            ConfigurationId = 1,
                            CPU = "Apple M4 10-core",
                            Color = "Space Black",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GraphicsCard = "10-core GPU",
                            OperatingSystem = "macOS Sequoia",
                            ProductId = 2,
                            RAM = "16 GB",
                            ScreenSize = "14.2 inch",
                            ScreenTechnology = "Liquid Retina XDR display",
                            Storage = "512 GB SSD",
                            Weight = "1.55 kg"
                        },
                        new
                        {
                            ConfigurationId = 2,
                            CPU = "Intel Core Ultra 9 185H",
                            Color = "Platinum",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GraphicsCard = "NVIDIA GeForce RTX 4070 8GB GDDR6",
                            OperatingSystem = "Windows 11 Pro",
                            ProductId = 4,
                            RAM = "32 GB LPDDR5x",
                            ScreenSize = "16.3 inch",
                            ScreenTechnology = "OLED Touch 4K+ (3840x2400)",
                            Storage = "1 TB PCIe 4.0 NVMe",
                            Weight = "2.13 kg"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.OTPCode", b =>
                {
                    b.Property<int>("OTPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTPId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.HasKey("OTPId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email", "Code");

                    b.ToTable("OTPCodes", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("PointsUsed")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("StatusId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOptions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("OrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Description = "Đơn hàng đang chờ xử lý",
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Description = "Đơn hàng đang được chuẩn bị",
                            StatusName = "Processing"
                        },
                        new
                        {
                            StatusId = 3,
                            Description = "Đơn hàng đã được giao cho đơn vị vận chuyển",
                            StatusName = "Shipped"
                        },
                        new
                        {
                            StatusId = 4,
                            Description = "Đơn hàng đã giao thành công",
                            StatusName = "Delivered"
                        },
                        new
                        {
                            StatusId = 5,
                            Description = "Đơn hàng đã bị hủy",
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            StatusId = 6,
                            Description = "Đơn hàng đã được hoàn trả / hoàn tiền",
                            StatusName = "Returned"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TokenId");

                    b.HasIndex("Email");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.PhoneConfiguration", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationId"));

                    b.Property<string>("Battery")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CPU")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Camera")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cores")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalStorage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ports")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RAM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Screen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ScreenTechnology")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Threads")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("PhoneConfigurations", null, t =>
                        {
                            t.HasTrigger("PhoneConfigTrigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            ConfigurationId = 1,
                            Battery = "Li-Ion, sạc nhanh 45W",
                            CPU = "Apple A18 Pro",
                            Camera = "Chính 48 MP & Phụ 48 MP, 12 MP",
                            Color = "Titan Sa Mạc",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalStorage = "256 GB",
                            OperatingSystem = "iOS 18",
                            ProductId = 1,
                            RAM = "8 GB",
                            Screen = "6.9-inch Super Retina XDR"
                        },
                        new
                        {
                            ConfigurationId = 2,
                            Battery = "5000 mAh, sạc nhanh 45W",
                            CPU = "Snapdragon 8 Gen 3 for Galaxy",
                            Camera = "200 MP & Phụ 50 MP, 12 MP, 10 MP",
                            Color = "Xám Titan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalStorage = "256 GB",
                            OperatingSystem = "Android 14, One UI 6.1",
                            ProductId = 3,
                            RAM = "12 GB",
                            Screen = "6.8-inch Dynamic AMOLED 2X"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[ImageId] IS NOT NULL");

                    b.HasIndex("SKU");

                    b.HasIndex("StatusId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasTrigger("ProductTrigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Apple",
                            CategoryId = 1,
                            Color = "Titan Sa Mạc",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "iPhone 16 Pro Max 256GB",
                            OldPrice = 36990000m,
                            Price = 34990000m,
                            SKU = "IP16PM256",
                            ShortDescription = "Chip A18 Pro, Apple Intelligence, Màn hình 6.9 inch Super Retina XDR.",
                            StatusId = (byte)1,
                            StockCode = "SC-IP16PM256"
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "Apple",
                            CategoryId = 2,
                            Color = "Space Black",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MacBook Pro 14 inch M4",
                            OldPrice = 45990000m,
                            Price = 42990000m,
                            SKU = "MBP14M4",
                            ShortDescription = "Chip M4 tiên tiến, 16GB RAM, 512GB SSD, Màn hình Liquid Retina XDR.",
                            StatusId = (byte)1,
                            StockCode = "SC-MBP14M4"
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Samsung",
                            CategoryId = 1,
                            Color = "Xám Titan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Samsung Galaxy S24 Ultra 256GB",
                            OldPrice = 35990000m,
                            Price = 33990000m,
                            SKU = "S24U256",
                            ShortDescription = "Galaxy AI, Khung viền Titan, Camera 200MP zoom quang 5x.",
                            StatusId = (byte)1,
                            StockCode = "SC-S24U256"
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "Dell",
                            CategoryId = 2,
                            Color = "Platinum",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dell XPS 16 (2026)",
                            OldPrice = 69990000m,
                            Price = 65990000m,
                            SKU = "DXPS162026",
                            ShortDescription = "Intel Core Ultra 9, 32GB RAM, 1TB SSD, RTX 4070, Màn hình 4K+ OLED Touch.",
                            StatusId = (byte)1,
                            StockCode = "SC-DXPS16"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImagePath")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", null, t =>
                        {
                            t.HasTrigger("ProductImageTrigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = new byte[0],
                            IsPrimary = true,
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = new byte[0],
                            IsPrimary = false,
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = new byte[0],
                            IsPrimary = true,
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = new byte[0],
                            IsPrimary = true,
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagePath = new byte[0],
                            IsPrimary = true,
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ProductOption", b =>
                {
                    b.Property<int>("ProductOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductOptionId"));

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOptions", (string)null);

                    b.HasData(
                        new
                        {
                            ProductOptionId = 1,
                            AdditionalPrice = 0m,
                            DisplayOrder = 1,
                            GroupName = "Màu sắc",
                            IsActive = true,
                            OptionName = "Titan Sa Mạc",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 2,
                            AdditionalPrice = 0m,
                            DisplayOrder = 2,
                            GroupName = "Màu sắc",
                            IsActive = true,
                            OptionName = "Titan Tự Nhiên",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 3,
                            AdditionalPrice = 0m,
                            DisplayOrder = 3,
                            GroupName = "Màu sắc",
                            IsActive = true,
                            OptionName = "Titan Đen",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 4,
                            AdditionalPrice = 0m,
                            DisplayOrder = 4,
                            GroupName = "Màu sắc",
                            IsActive = true,
                            OptionName = "Titan Trắng",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 5,
                            AdditionalPrice = 0m,
                            DisplayOrder = 1,
                            GroupName = "Bộ nhớ trong",
                            IsActive = true,
                            OptionName = "256GB",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 6,
                            AdditionalPrice = 5000000m,
                            DisplayOrder = 2,
                            GroupName = "Bộ nhớ trong",
                            IsActive = true,
                            OptionName = "512GB",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 7,
                            AdditionalPrice = 11000000m,
                            DisplayOrder = 3,
                            GroupName = "Bộ nhớ trong",
                            IsActive = true,
                            OptionName = "1TB",
                            ProductId = 1
                        },
                        new
                        {
                            ProductOptionId = 8,
                            AdditionalPrice = 0m,
                            DisplayOrder = 1,
                            GroupName = "RAM",
                            IsActive = true,
                            OptionName = "16GB",
                            ProductId = 2
                        },
                        new
                        {
                            ProductOptionId = 9,
                            AdditionalPrice = 5000000m,
                            DisplayOrder = 2,
                            GroupName = "RAM",
                            IsActive = true,
                            OptionName = "24GB",
                            ProductId = 2
                        },
                        new
                        {
                            ProductOptionId = 10,
                            AdditionalPrice = 0m,
                            DisplayOrder = 1,
                            GroupName = "SSD",
                            IsActive = true,
                            OptionName = "512GB",
                            ProductId = 2
                        },
                        new
                        {
                            ProductOptionId = 11,
                            AdditionalPrice = 5000000m,
                            DisplayOrder = 2,
                            GroupName = "SSD",
                            IsActive = true,
                            OptionName = "1TB",
                            ProductId = 2
                        },
                        new
                        {
                            ProductOptionId = 16,
                            AdditionalPrice = 0m,
                            DisplayOrder = 1,
                            GroupName = "Bộ nhớ trong",
                            IsActive = true,
                            OptionName = "256GB",
                            ProductId = 3
                        },
                        new
                        {
                            ProductOptionId = 17,
                            AdditionalPrice = 3500000m,
                            DisplayOrder = 2,
                            GroupName = "Bộ nhớ trong",
                            IsActive = true,
                            OptionName = "512GB",
                            ProductId = 3
                        },
                        new
                        {
                            ProductOptionId = 18,
                            AdditionalPrice = 0m,
                            DisplayOrder = 1,
                            GroupName = "Màn hình",
                            IsActive = true,
                            OptionName = "OLED Touch 4K+",
                            ProductId = 4
                        },
                        new
                        {
                            ProductOptionId = 19,
                            AdditionalPrice = -4000000m,
                            DisplayOrder = 2,
                            GroupName = "Màn hình",
                            IsActive = true,
                            OptionName = "FHD+ Non-Touch",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ProductStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("StatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusId");

                    b.ToTable("ProductStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = (byte)1,
                            Description = "Sản phẩm có sẵn, đang kinh doanh",
                            StatusName = "Available"
                        },
                        new
                        {
                            StatusId = (byte)2,
                            Description = "Sản phẩm đã hết hàng",
                            StatusName = "Out of Stock"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Quản trị viên cấp cao nhất",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Nhân viên quản lý",
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Khách hàng",
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.SpinHistory", b =>
                {
                    b.Property<int>("SpinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpinId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SpinAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpinResult")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("SpinId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("CustomerId", "SpinAt");

                    b.ToTable("SpinHistories", (string)null);
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = new byte[] { 147, 186, 166, 224, 128, 110, 18, 16, 209, 138, 14, 3, 140, 101, 193, 223, 134, 242, 179, 21, 25, 20, 208, 182, 112, 183, 17, 199, 15, 222, 119, 93 },
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@example.com",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            PasswordHash = new byte[] { 176, 65, 192, 174, 179, 91, 176, 250, 74, 166, 104, 202, 90, 146, 11, 89, 1, 150, 253, 175, 154, 0, 235, 133, 44, 155, 127, 77, 18, 60, 198, 214 },
                            RoleId = 3,
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.UserPointHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("HistoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("UserPointHistories", (string)null);

                    b.HasData(
                        new
                        {
                            HistoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Points = 500,
                            Reason = "Tích điểm đơn hàng #1001 - Giao thành công"
                        },
                        new
                        {
                            HistoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Points = 300,
                            Reason = "Tích điểm đơn hàng #1002 - Giao thành công"
                        },
                        new
                        {
                            HistoryId = 3,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Points = -200,
                            Reason = "Dùng điểm thanh toán đơn hàng #1003"
                        },
                        new
                        {
                            HistoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Points = 150,
                            Reason = "Tích điểm đơn hàng #1004 - Giao thành công"
                        },
                        new
                        {
                            HistoryId = 5,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Points = 100,
                            Reason = "Thưởng sự kiện Vòng quay may mắn"
                        },
                        new
                        {
                            HistoryId = 6,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Points = -100,
                            Reason = "Hoàn trả điểm đơn hàng #1005 - Hoàn hàng"
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.UserVoucher", b =>
                {
                    b.Property<int>("UserVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserVoucherId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("UserVoucherId");

                    b.HasIndex("OrderId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("CustomerId", "VoucherId", "IsUsed")
                        .HasFilter("[IsUsed] = 0");

                    b.ToTable("UserVouchers", (string)null);

                    b.HasData(
                        new
                        {
                            UserVoucherId = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            IsUsed = false,
                            VoucherId = 1
                        },
                        new
                        {
                            UserVoucherId = 2,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            IsUsed = false,
                            VoucherId = 2
                        },
                        new
                        {
                            UserVoucherId = 3,
                            AssignedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            IsUsed = false,
                            VoucherId = 3
                        },
                        new
                        {
                            UserVoucherId = 4,
                            AssignedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            IsUsed = false,
                            VoucherId = 4
                        },
                        new
                        {
                            UserVoucherId = 5,
                            AssignedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            IsUsed = false,
                            VoucherId = 5
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VoucherId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vouchers", (string)null);

                    b.HasData(
                        new
                        {
                            VoucherId = 1,
                            Code = "WELCOME50",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Voucher chào mừng thành viên mới - giảm 50.000đ",
                            DiscountType = 2,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinOrderValue = 500000m,
                            Quantity = 0,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedCount = 0,
                            Value = 50000m
                        },
                        new
                        {
                            VoucherId = 2,
                            Code = "SALE10PCT",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giảm 10% tối đa 100.000đ cho đơn từ 1.000.000đ",
                            DiscountType = 1,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 100000m,
                            MinOrderValue = 1000000m,
                            Quantity = 500,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedCount = 0,
                            Value = 10m
                        },
                        new
                        {
                            VoucherId = 3,
                            Code = "SILVER100",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ưu đãi hạng Bạc - giảm 100.000đ cho đơn từ 2.000.000đ",
                            DiscountType = 2,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinOrderValue = 2000000m,
                            Quantity = 200,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedCount = 0,
                            Value = 100000m
                        },
                        new
                        {
                            VoucherId = 4,
                            Code = "GOLD15PCT",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ưu đãi hạng Vàng - giảm 15% tối đa 300.000đ",
                            DiscountType = 1,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 300000m,
                            MinOrderValue = 5000000m,
                            Quantity = 100,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedCount = 0,
                            Value = 15m
                        },
                        new
                        {
                            VoucherId = 5,
                            Code = "DIAMOND20",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ưu đãi hạng Kim Cương - giảm 20% tối đa 1.000.000đ",
                            DiscountType = 1,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 1000000m,
                            MinOrderValue = 10000000m,
                            Quantity = 50,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedCount = 0,
                            Value = 20m
                        });
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Cart", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.CartDetail", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Cart", "Cart")
                        .WithMany("Details")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.CrossSellRule", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "SuggestedProduct")
                        .WithMany()
                        .HasForeignKey("SuggestedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "TriggerProduct")
                        .WithMany("CrossSellRulesTrigger")
                        .HasForeignKey("TriggerProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SuggestedProduct");

                    b.Navigation("TriggerProduct");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Customer", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.CustomerTier", "Tier")
                        .WithMany("Customers")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ExportReceipt", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("WEBBANDIENTHOAI.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ExportReceiptDetail", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.ExportReceipt", "ExportReceipt")
                        .WithMany("ExportReceiptDetails")
                        .HasForeignKey("ExportReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("ExportDetails")
                        .HasForeignKey("ProductId");

                    b.Navigation("ExportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ImportReceiptDetail", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.ImportReceipt", "ImportReceipt")
                        .WithMany("Details")
                        .HasForeignKey("ImportReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ProductId");

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Inventory", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("Inventory")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.InventoryHistory", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Inventory", "Inventory")
                        .WithMany("History")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.LaptopConfiguration", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithOne("LaptopConfiguration")
                        .HasForeignKey("WEBBANDIENTHOAI.Models.LaptopConfiguration", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Order", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.OrderDetail", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.PhoneConfiguration", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithOne("PhoneConfiguration")
                        .HasForeignKey("WEBBANDIENTHOAI.Models.PhoneConfiguration", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Product", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.ProductImage", "PrimaryImage")
                        .WithOne()
                        .HasForeignKey("WEBBANDIENTHOAI.Models.Product", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WEBBANDIENTHOAI.Models.ProductStatus", "ProductStatus")
                        .WithMany("Products")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PrimaryImage");

                    b.Navigation("ProductStatus");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ProductImage", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ProductOption", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Product", "Product")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.SpinHistory", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.User", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.UserPointHistory", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Customer", "Customer")
                        .WithMany("PointHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Order", "Order")
                        .WithMany("PointHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.UserVoucher", b =>
                {
                    b.HasOne("WEBBANDIENTHOAI.Models.Customer", "Customer")
                        .WithMany("UserVouchers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEBBANDIENTHOAI.Models.Order", "Order")
                        .WithMany("UserVouchers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WEBBANDIENTHOAI.Models.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Cart", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Customer", b =>
                {
                    b.Navigation("PointHistories");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.CustomerTier", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ExportReceipt", b =>
                {
                    b.Navigation("ExportReceiptDetails");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ImportReceipt", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Inventory", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PointHistories");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("CrossSellRulesTrigger");

                    b.Navigation("ExportDetails");

                    b.Navigation("Images");

                    b.Navigation("ImportDetails");

                    b.Navigation("Inventory");

                    b.Navigation("LaptopConfiguration");

                    b.Navigation("OrderDetails");

                    b.Navigation("PhoneConfiguration");

                    b.Navigation("ProductOptions");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.ProductStatus", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WEBBANDIENTHOAI.Models.Voucher", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
